default_stages: [commit]

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        name: terraform-fmt
        description: "Run 'terraform fmt' for format"
        args: [recursive]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-gcs2spanner
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "./README.md",
            "./modules/gcs2spanner/",
          ]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-monitoring-tools
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "./README.md",
            "./modules/monitoring-tools/",
          ]

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:
      - id: terraform-docs-go
        name: terraform-docs-microservices
        args:
          [
            "markdown",
            "table",
            "--output-file",
            "./README.md",
            "./modules/microservices/",
          ]
