default_stages: [commit]

repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_fmt
        name: terraform-fmt
        description: "Run 'terraform fmt' for format"
        args: [recursive]
